publisher = "datadog"

[datadog]
api_key = "blahbla"
site = "us5.datadoghq.com"

[targets."label1"]
host = "10.0.0.1"
tags = ["isp:foo", "cage:bar", "rack:baz"]

[targets."label2"]
host = "10.0.0.2"
tags = ["isp:bla"]

[targets]
label3 = "10.0.0.3"
